# Generated by Django 5.1.15 on 2026-04-19 12:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Фонове зображення')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показувати на головній')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_web.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('subtotal_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_label', models.CharField(blank=True, max_length=255)),
                ('birthday_verification_required', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено')], default='new', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('slug', models.SlugField(blank=True, max_length=230, null=True, unique=True, verbose_name='Slug')),
                ('brand', models.CharField(default='Vaporesso', max_length=100, verbose_name='Бренд')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
                ('glycerin_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Гліцерин (грн)')),
                ('stock_qty', models.PositiveIntegerField(blank=True, help_text='Залиште порожнім, якщо облік залишків для товару не ведеться.', null=True, verbose_name='Залишок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото товару')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.category', verbose_name='Категорія')),
                ('compatible_products', models.ManyToManyField(blank=True, related_name='compatible_with', to='app_web.product', verbose_name='Супутні товари')),
                ('similar_products', models.ManyToManyField(blank=True, related_name='similar_to', to='app_web.product', verbose_name='Схожі товари')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200, verbose_name='Назва товару (snapshot)')),
                ('variant_name', models.CharField(default='Стандарт', max_length=100, verbose_name='Варіант')),
                ('extra', models.CharField(blank=True, default='', max_length=100, verbose_name='Додатково')),
                ('glycerin_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Гліцерин (грн)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_web.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_web.product')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='По батькові')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефону')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса доставки')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Код скидання пароля',
                'verbose_name_plural': 'Коди скидання пароля',
                'indexes': [models.Index(fields=['email', 'created_at'], name='app_web_pas_email_885d7a_idx'), models.Index(fields=['email', 'code', 'is_used'], name='app_web_pas_email_04c5b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percent', 'Відсоток'), ('fixed', 'Фіксована сума')], max_length=20, verbose_name='Тип знижки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значення')),
                ('start_date', models.DateTimeField(verbose_name='Початок дії')),
                ('end_date', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='app_web.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Знижка на товар',
                'verbose_name_plural': 'Знижки на товари',
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='app_web_pro_is_acti_8b1dd1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва (колір/смак)')),
                ('stock_qty', models.PositiveIntegerField(blank=True, help_text='Залиште порожнім, якщо залишок контролюється на рівні товару.', null=True, verbose_name='Залишок варіанту')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='Фото варіанту')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='app_web.product')),
            ],
            options={
                'verbose_name': 'Варіант товару',
                'verbose_name_plural': 'Варіанти товарів',
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='unique_variant_name_per_product')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='Схвалено')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app_web.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_review_per_user_product')],
            },
        ),
    ]
