# Generated by Django 6.0.3 on 2026-03-22 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_alter_profile_address_alter_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото товару')),
                ('is_active', models.BooleanField(default=True, verbose_name='У наявності')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
