# Generated by Django 6.0.3 on 2026-03-22 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Vaporesso', max_length=100, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_products',
            field=models.ManyToManyField(blank=True, related_name='compatible_with', to='app_web.product', verbose_name='Супутні товари (картриджі тощо)'),
        ),
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, related_name='similar_to', to='app_web.product', verbose_name='Схожі товари'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, verbose_name='Артикул'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва (Колір/Смак)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='Фото варіації')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='app_web.product')),
            ],
        ),
    ]
