# Generated by Codex on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0006_product_brand_product_compatible_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='birthday_verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
