# Generated by Django 6.0.3 on 2026-04-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0010_profile_birth_date_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(blank=True, help_text='Залиште порожнім, якщо облік залишків для товару не ведеться.', null=True, verbose_name='Залишок'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_qty',
            field=models.PositiveIntegerField(blank=True, help_text='Залиште порожнім, якщо залишок контролюється на рівні товару.', null=True, verbose_name='Залишок варіанту'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/', verbose_name='Фото варіанту'),
        ),
    ]
