# Generated by Django 6.0.3 on 2026-04-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0011_product_stock_qty_productvariant_stock_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=230, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
