# Generated by Django 6.0.3 on 2026-04-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0013_populate_product_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
    ]
