# Generated by Django 6.0.3 on 2026-04-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0014_productvariant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extra',
            field=models.CharField(blank=True, default='Гліцерин', max_length=100, verbose_name='Додатково'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='glycerin_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Гліцерин (грн)'),
        ),
        migrations.AddField(
            model_name='product',
            name='glycerin_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Гліцерин (грн)'),
        ),
    ]
