# Generated by Django 6.0.3 on 2026-04-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0015_orderitem_extra_orderitem_glycerin_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Додатково'),
        ),
    ]
