# Generated by Django 6.0.3 on 2026-04-10 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0018_order_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percent', 'Відсоток'), ('fixed', 'Фіксована сума')], max_length=20, verbose_name='Тип знижки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значення')),
                ('start_date', models.DateTimeField(verbose_name='Початок дії')),
                ('end_date', models.DateTimeField(verbose_name='Кінець дії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='app_web.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Знижка на товар',
                'verbose_name_plural': 'Знижки на товари',
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='app_web_pro_is_acti_8b1dd1_idx')],
            },
        ),
    ]
