# Generated by Django 5.1.15 on 2026-04-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0019_productdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='includes_glycerin',
            field=models.BooleanField(default=False, verbose_name='У комплекті є гліцерин'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_products', to='app_web.category', verbose_name='Підкатегорія'),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва бренду')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('categories', models.ManyToManyField(blank=True, related_name='brands', to='app_web.category', verbose_name='Категорії')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app_web.brand', verbose_name='Бренд'),
        ),
    ]
