# Generated by Codex on 2026-04-20

from django.db import migrations
from django.utils.text import slugify


BRAND_NAME_ALIASES = {
    "elf-bar": "Elf Bar",
    "elfbar": "Elf Bar",
    "in-bottle": "Puzzle in Bottle",
    "lost-vape": "Lost Vape",
    "lostvaspe": "Lost Vape",
    "lostvape": "Lost Vape",
    "oxva": "OXVA",
}

SUBCATEGORY_ENABLED_CATEGORIES = {
    "Ароматизатори",
    "Девайси",
    "Випаровувачі",
    "Картриджі",
}


def canonicalize_brand_name(value):
    normalized = " ".join(str(value or "").strip().split())
    if not normalized:
        return ""
    return BRAND_NAME_ALIASES.get(slugify(normalized), normalized)


def build_unique_slug(model, value):
    base = slugify(value) or "brand"
    slug = base
    counter = 2
    while model.objects.filter(slug=slug).exists():
        slug = f"{base}-{counter}"
        counter += 1
    return slug


def forwards(apps, schema_editor):
    Brand = apps.get_model("app_web", "Brand")
    Category = apps.get_model("app_web", "Category")
    Product = apps.get_model("app_web", "Product")

    category_cache = {category.id: category for category in Category.objects.all()}
    brand_cache = {brand.name.casefold(): brand for brand in Brand.objects.all()}
    subcategory_cache = {}
    target_category_ids = set(
        Category.objects.filter(parent__isnull=True, name__in=SUBCATEGORY_ENABLED_CATEGORIES).values_list("id", flat=True)
    )

    for product in Product.objects.select_related("category", "subcategory").order_by("id"):
        category = category_cache.get(product.category_id)
        top_category = category
        subcategory = category_cache.get(product.subcategory_id) if product.subcategory_id else None

        if category and category.parent_id:
            subcategory = category
            top_category = category_cache.get(category.parent_id)

        brand_name = canonicalize_brand_name(product.brand)
        brand = None
        if brand_name:
            brand = brand_cache.get(brand_name.casefold())
            if brand is None:
                brand = Brand.objects.create(name=brand_name, slug=build_unique_slug(Brand, brand_name))
                brand_cache[brand_name.casefold()] = brand
            if top_category:
                brand.categories.add(top_category)

        if not subcategory and top_category and top_category.id in target_category_ids and brand:
            subcategory_key = (top_category.id, brand.name.casefold())
            subcategory = subcategory_cache.get(subcategory_key)
            if subcategory is None:
                subcategory = Category.objects.filter(parent=top_category, name__iexact=brand.name).first()
                if subcategory is None:
                    subcategory = Category.objects.create(parent=top_category, name=brand.name, is_featured=False)
                subcategory_cache[subcategory_key] = subcategory

        update_fields = []

        if top_category and product.category_id != top_category.id:
            product.category_id = top_category.id
            update_fields.append("category")

        if subcategory:
            if product.subcategory_id != subcategory.id:
                product.subcategory_id = subcategory.id
                update_fields.append("subcategory")
        elif product.subcategory_id:
            product.subcategory = None
            update_fields.append("subcategory")

        if brand and product.brand_ref_id != brand.id:
            product.brand_ref_id = brand.id
            update_fields.append("brand_ref")

        if brand_name and product.brand != brand_name:
            product.brand = brand_name
            update_fields.append("brand")

        if product.glycerin_price and product.glycerin_price > 0 and not product.includes_glycerin:
            product.includes_glycerin = True
            update_fields.append("includes_glycerin")

        if update_fields:
            product.save(update_fields=list(dict.fromkeys(update_fields)))


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0020_product_includes_glycerin_product_subcategory_brand_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
