# Generated by Django 5.1.15 on 2026-04-20 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0021_backfill_product_taxonomy_and_glycerin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Назва характеристики')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_highlight', models.BooleanField(default=False, verbose_name='Виділити неоном')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='app_web.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика товару',
                'verbose_name_plural': 'Характеристики товарів',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
